theme: jekyll-theme-hacker
<section id="downloads">
          
            <a href="https://github.com/pages-themes/hacker/zipball/master" class="btn">Download as .zip</a>
            <a href="https://github.com/pages-themes/hacker/tarball/master" class="btn">Download as .tar.gz</a>
          
          <a href="https://github.com/pages-themes/hacker" class="btn btn-github"><span class="icon"></span>View on GitHub</a>
        </section>

